# CMake generated Testfile for 
# Source directory: /Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test
# Build directory: /Users/gustavnielsen/Documents/Kode.nosync/relic-target/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_err "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_err")
set_tests_properties(test_err PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;14;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_bn "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_bn")
set_tests_properties(test_bn PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;18;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_dv "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_dv")
set_tests_properties(test_dv PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;22;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_fp "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_fp")
set_tests_properties(test_fp PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;26;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_fpx "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_fpx")
set_tests_properties(test_fpx PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;30;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_fb "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_fb")
set_tests_properties(test_fb PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;34;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_fbx "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_fbx")
set_tests_properties(test_fbx PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;38;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_ep "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_ep")
set_tests_properties(test_ep PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;42;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_epx "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_epx")
set_tests_properties(test_epx PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;46;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_eb "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_eb")
set_tests_properties(test_eb PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;50;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_ed "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_ed")
set_tests_properties(test_ed PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;54;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_ec "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_ec")
set_tests_properties(test_ec PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;58;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_pc "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_pc")
set_tests_properties(test_pc PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;62;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_pp "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_pp")
set_tests_properties(test_pp PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;66;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_md "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_md")
set_tests_properties(test_md PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;70;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_cp "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_cp")
set_tests_properties(test_cp PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;74;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_mpc "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_mpc")
set_tests_properties(test_mpc PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;78;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_rand "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_rand")
set_tests_properties(test_rand PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;81;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
add_test(test_core "/Users/gustavnielsen/Documents/Kode.nosync/relic-target/bin/test_core")
set_tests_properties(test_core PROPERTIES  _BACKTRACE_TRIPLES "/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;10;add_test;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;82;ADD_MODULE;/Users/gustavnielsen/Documents/Kode.nosync/relic-0.7.0/test/CMakeLists.txt;0;")
